# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11fe2274d0a4b7a5a86a6a3294c3eb3c1dbf5337b7a5af9c0974870fe742b95b08a15f0c5f3eb2a722fa775adea37b6f325beccd0f00944ee46fa48974ec3e52

test:
  secret_key_base: bbe48fb9bc00f8e1cd75924413b4013af79fb67a25ac6e30b3fc4009d908fbf6601d51c57e4d62504ae0482a00310a2014bfe841fdcc8999845df31510ba1ded

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
